%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

%wygenerowane z erlsom:write_xsd_hrl_file("books.xsd", "books.hrl", []).

-record('BookForm', {anyAttribs, 'id', 'author', 'title', 'genre', 'price', 'pub_date', 'review'}).
-record('BooksForm', {anyAttribs, 'book'}).
