%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-ifndef(ERLSOM_ANY_ATTRIB_TYPES).
-define(ERLSOM_ANY_ATTRIB_TYPES, true).
-type anyAttrib()  :: {{string(),    %% name of the attribute
                        string()},   %% namespace
                       string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.
-endif.

-ifndef(ERLSOM_QNAME_TYPES).
-define(ERLSOM_QNAME_TYPES, true).
%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
                localPart :: string(),
                prefix :: string(),
                mappedPrefix :: string()}).
-endif.



-record(location, {anyAttribs :: anyAttribs(),
	latitude :: float() | 'NaN' | 'INF' | '-INF',
	longitude :: float() | 'NaN' | 'INF' | '-INF'}).

-type location() :: #location{}.


-record(no2, {anyAttribs :: anyAttribs(),
	precision :: float() | 'NaN' | 'INF' | '-INF',
	value :: float() | 'NaN' | 'INF' | '-INF'}).

-type no2() :: #no2{}.


-record(data, {anyAttribs :: anyAttribs(),
	no2 :: no2(),
	no2_strat :: no2(),
	no2_trop :: no2()}).

-type data() :: #data{}.


-record(element, {anyAttribs :: anyAttribs(),
	data :: data(),
	location :: location(),
	time :: string()}).

-type element() :: #element{}.


-record(measurements, {anyAttribs :: anyAttribs(),
	element :: [element()]}).

-type measurements() :: #measurements{}.